### ISSUE TITLE
Proposal: extras object

### ISSUE THREAD

**Issue by ryands** [ryands/roast-spec#4]
An "extras" object for extra metadata related to the person logging a roast's specific usecase might provide useful flexibility.

Example:

```toml
[extras]
    photo = "https://cdn.myblog.org/photos/coffee_roast_10.png"
    whatever = "..."
```
